💄 refactor button style & add button components
ashby-git/counter pull request #3
Opened 2021-03-27 07:25 UTC by ashby-git

I removed some of the irrelevant styling for the circular button.
Also added, main circular button base and 3 specific buttons.

2021-03-27 07:30 UTC, DanArcherOnline requested changes
the button has only been recreated so its not a refactor. please change the title to reflect the commits in this PR

2021-03-27 07:39 UTC, DanArcherOnline requested changes

2021-03-27 07:39 UTC, DanArcherOnline commented on src/components/button/circular-button.styles.scss
> +  width: 100px;
has it been decided that the buttons will be 100px?
if they will be a different size, best to change it now.
if 100px is fine for the final design, no changes necessary.

2021-03-27 07:39 UTC, DanArcherOnline commented on src/components/button/circular-button.styles.scss
> +  color: white;
you have specified the color twice

2021-03-27 07:39 UTC, DanArcherOnline commented on src/components/button/refresh-circular-button.component.jsx
> +    <CircularButton className='button'>
don't need the className coz its already set in the CircularButton component.
Also might be better to change the name. Coz you dont really say refresh a counter. maybe reset is better. what do you think?

2021-04-10 07:10 UTC, ashby-git commented
I have made the changes you requested, please review the updated code

2021-04-10 07:16 UTC, DanArcherOnline approved these changes
LGTM

2021-04-10 07:16 UTC, merged